### ISSUE TITLE
BUG：对一个麦位静音后用户上到此麦位，再对此麦位解除静音，此时用户说话没有声音

### ISSUE THREAD

**Issue by MinTate** [tencentyun/TUIVoiceRoom#16]
sdkappid: xxxx
roomid:
userid:
时间点：xxxx
版本信息：比如：TXLiteAVSDK_TRTC_9.4.10701
日志文件：位置：/sdcard/Android/data/[packagename]/files/log 
复习路径/录屏：

**Comment by wufeng2022** [comment]
sdkappid: 1400575928
roomid:10039510
userid:10001822
时间点：2022年1月7日16时46分左右
版本信息：com.tencent.liteav:LiteAVSDK_TRTC:latest.release
[log.zip](https://github.com/tencentyun/TUIVoiceRoom/files/7827684/log.zip)

https://user-images.githubusercontent.com/97281930/148518982-046afc47-9a7b-4537-9c43-07bd53f6f878.mp4

**Comment by masonqiaoA** [comment]
Hi wufeng2022,

感谢您使用腾讯云trtc！

我查看了一下你上传的日志， 当前登录的用户是10001822，
10001822用户收到座位静音被取消的通知（onSeatMute）后，调用了muteRemoteAudio接口去解除静音了。
> [I][2022-01-07 +8.0 16:50:52.881][27447, 27447*][TXRoomService][, , 0][onSeatMute 1 mute:false
> I][2022-01-07 +8.0 16:50:52.887][27447, 27447*][com.tencent.liteav.trtcvoiceroom.model.impl.TRTCVoiceRoomImpl][, , 0][mute trtc audio, user id:10001822
> [I][2022-01-07 +8.0 16:50:52.887][27447, 27447*][VoiceRoomTRTCService][, , 0][mute remote audio, user id:10001822 mute:false

因为对于本地自己的话，是需要调用muteLocalAudio来开启或者关闭静音操作的。
需要禁止或者开启远端用户（类似于停止订阅远端音频流）的时候才需要使用muteRemoteAudio来操作的，调用远端开启音频进口是不能操作自己的音频设备的。

请检查一下自己的代码是否使用错了接口api，你这里的场景应该是要使用muteLocalAudio接口开启音频的，望知悉，有问题可以随时沟通。



本地禁止和远端禁止音频的接口api
   ```
    /**
     * 开启本地静音
     * @param mute 是否静音
     */
    public abstract void muteLocalAudio(boolean mute);


 //////////////////////////////////////////////////////////
    //
    //                 远端用户接口
    //
    //////////////////////////////////////////////////////////
    /**
     * 静音某一个用户的声音
     *
     * @param userId 用户id
     * @param mute true:静音 false：解除静音
     */
    public abstract void muteRemoteAudio(String userId, boolean mute);


```

**Comment by wufeng2022** [comment]
@qiaolong1996
那为什么此用户下麦后再上麦又正常可以说话了呢

**Comment by wufeng2022** [comment]
现在的情景是房主对用户所在麦位解除静音，难道不是解除静音后用户就能说话了吗，跟muteLocalAudio有啥关系？

**Comment by wufeng2022** [comment]
现在的情景是房主对用户所在麦位解除静音，难道不是解除静音后用户就能说话了吗，跟muteLocalAudio有啥关系？

**Comment by wufeng2022** [comment]
现在的情景是房主对用户所在麦位解除静音，难道不是解除静音后用户就能说话了吗，跟muteLocalAudio有啥关系？

**Comment by masonqiaoA** [comment]
@wufeng2022 
对麦位静音，这个麦位的人不能说话，但是解除麦位静音后，只是解除了座位静音的状态。
麦克风能够说话有两个状态决定： 1： 座位静音状态  2： 本身用户是否打开了麦克风状态

解除静音后，如果之前麦克风本身是关闭状态，是不能打开的，是需要主动调用muteLocalAudio（true） 打开的，这个不能由房主控制。

**Comment by wufeng2022** [comment]
好的，谢谢，这边在调试下
