### ISSUE TITLE
OC版的源码有吗

### ISSUE THREAD

**Issue by WeaponChan** [tencentyun/TUIVoiceRoom#3]
你好，iOS端  实时语音聊天室有OC源码吗

**Comment by RipperLiew** [comment]
> 你好，iOS端实时语音聊天室有OC源码吗？

尊敬的腾讯云用户，您好：
目前TUIVoiceRoom源码 iOS 端的 Model 层支持 OC 版本，UI 层支持 Swift 版本。但 UI 层目前暂不考虑提供 OC 版本，若您需要可以选择以下方案：
1、混编 Swift 版本。
2、OC 版本参考 Swift 版本实现。
3、根据自己的业务和 UI 设计，自行实现。
其中，TUIVoiceRoom 的 Model 层源码为 OC，调用 TRTC 的 API，可以参考 Model 层源码。

**Comment by onesmalldog** [comment]
> 你好，iOS端 实时语音聊天室有OC源码吗

尊敬的腾讯云用户，您好：
目前TUIVoiceRoom源码 iOS 端的 Model 层支持 OC 版本，UI 层支持 Swift 版本。但 UI 层目前暂不考虑提供 OC 版本，若您需要可以选择以下方案：
1、混编 Swift 版本。
2、OC 版本参考 Swift 版本实现。
3、根据自己的业务和 UI 设计，自行实现。
其中，TUIVoiceRoom 的 Model 层源码为 OC，调用 TRTC 的 API，可以参考 Model 层源码。

**Comment by WeaponChan** [comment]
好滴，谢谢
